feat: separate release from docker publish

diff --git a/.github/actions/git-tag/action.yaml b/.github/actions/git-tag/action.yaml
--- a/.github/actions/git-tag/action.yaml
+++ b/.github/actions/git-tag/action.yaml
@@ -29,6 +29,14 @@ inputs:
     required: false
     default: username@users.noreply.github.com
     description: default git email
+  force-tag:
+    required: false
+    default: "false"
+    description: git force push tag
+outputs:
+  TAG_EXISTS:
+    description: tag exists or not
+    value: ${{ steps.git-tag.outputs.TAG_EXISTS }}
 
 runs:
   using: composite
@@ -50,14 +58,28 @@ runs:
         echo -e "${CYAN}[ INFO ] > git origin.${BLANK}"
         git -C ${{ inputs.git-workdir }} remote show origin
 
-        if [[ -n "${{ inputs.commit-sha }}" ]]
+        if [ "$(git tag -l "${{ inputs.tag-value }}")" ]
         then
-          COMMIT_TAG=${{ inputs.commit-sha }}
+          tag_exists=true
         else
-          COMMIT_TAG="current"
+          tag_exists=false
         fi
-        echo -e "${YELLOW}[ EXECUTING ] > tag ${PURPLE}${{ inputs.tag-value }}${YELLOW} on ${PURPLE}${COMMIT_TAG}${YELLOW} commit and push to destination ${PUSH_URL}${BLANK}"
-        git -C ${{ inputs.git-workdir }} tag -a ${{ inputs.tag-value }} ${{ inputs.commit-sha }} -m "${TAG_MSG}"
+        echo "TAG_EXISTS=${tag_exists}" >> "${GITHUB_OUTPUT}"
+
+        echo -e "${YELLOW}[ EXECUTING ] > tag ${PURPLE}${{ inputs.tag-value }}${YELLOW} on ${PURPLE}${{ inputs.commit-sha }}${YELLOW} commit and push to destination ${PUSH_URL}${BLANK}"
+        if [ "${tag_exists}" = 'true' ]
+        then
+          if [ "${{ inputs.force-tag }}" = 'true' ]
+          then
+            echo -e "${CYAN}[ INFO ] Force push tag${BLANK}"
+            git -C ${{ inputs.git-workdir }} tag -fa ${{ inputs.tag-value }} ${{ inputs.commit-sha }} -m "${TAG_MSG}"
+          else
+            echo -e "${RED}[ ERROR ] Tag already exists${BLANK}"
+            exit 1
+          fi
+        else
+          git -C ${{ inputs.git-workdir }} tag -a ${{ inputs.tag-value }} ${{ inputs.commit-sha }} -m "${TAG_MSG}"
+        fi
         git -C ${{ inputs.git-workdir }} push origin ${{ inputs.tag-value }} --push-option ${{ inputs.push-option }}
 
         if [ $? -eq 0 ]
